CREATE SEQUENCE auto_mem_id START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE NOCACHE;
CREATE SEQUENCE auto_novel_id START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE NOCACHE;
CREATE SEQUENCE auto_episode_id START WITH 1 INCREMENT BY 1 MAXVALUE 999999 CYCLE NOCACHE;
CREATE SEQUENCE auto_detail_id START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE NOCACHE;
CREATE SEQUENCE auto_bookmark_id START WITH 1 INCREMENT BY 1 MAXVALUE 999999 CYCLE NOCACHE;
CREATE SEQUENCE auto_comment_id START WITH 1 INCREMENT BY 1 MAXVALUE 99999999 CYCLE NOCACHE;
CREATE SEQUENCE auto_license_id START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE NOCACHE;
CREATE SEQUENCE auto_quest_id START WITH 1 INCREMENT BY 1 MAXVALUE 9999 CYCLE NOCACHE;